name: OGNN
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - python=3.10
  - pip
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pytorch-cuda=11.7
  - scikit-learn
  - tqdm
  - scipy
  - tensorboard
  - black
  - ipykernel
  - rdkit
  - pyyaml
  - pydantic
  - pip:
      - numpy==1.26.4
      - torchdata==0.5.1
      - torch-ema
      - deepchem
      - torch-scatter==2.1.1
      - torch-sparse==0.6.17
      - torch-cluster==1.6.1
      - torch-spline-conv==1.2.1
      - torch-geometric==2.4.0
      - --find-links https://data.pyg.org/whl/torch-1.13.0+cu117.html
