name: chem
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.20
  - pip
  - numpy=1.24.4
  - pandas=2.0.3
  - matplotlib=3.7.2
  - seaborn=0.13.2
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - ipykernel=6.29.5
  - rdkit=2024.03.5
  - pyqt=5.15.10
  - mkl-service=2.4.0
  - numexpr=2.7.3
  - bottleneck=1.3.7
  - joblib=1.4.2
  - psutil=6.0.0
  - sqlalchemy=2.0.32
  - pip:
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - idna==3.7
      - requests==2.32.3
      - urllib3==2.2.3
